//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class coordinator_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coordinator_profile()
        {
            this.coordinator_profile1 = new HashSet<coordinator_profile>();
        }

        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public int CoordinatorUserID { get; set; }
        public int SchoolId { get; set; }
        public bool IsPrimery { get; set; }
        public string CoordinatorName { get; set; }
        public string PhotoPath { get; set; }
        public string AcademicQualification { get; set; }
        public Nullable<bool> HasTOTCertificate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsProfileComplete { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> FirstLogin { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsRegisterComplete { get; set; }
        public string FatherName { get; set; }
        public string FaimlyName { get; set; }
        public string AcademicQualification2 { get; set; }
        public string AcademicQualification3 { get; set; }

        public virtual school school { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coordinator_profile> coordinator_profile1 { get; set; }
        public virtual coordinator_profile coordinator_profile2 { get; set; }
    }
}
