//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class funder_profile
    {
        public int Id { get; set; }
        public System.Guid RowGUID { get; set; }
        public int FunderUserID { get; set; } 
        public string FatherName { get; set; }
        public string FaimlyName { get; set; } 
        public Nullable<int> Country { get; set; } 
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string PartnerType { get; set; }
        public string TypeOfFunding { get; set; }
        
        public virtual lk_country lk_country { get; set; }
        public virtual user user { get; set; }
    }
}
