//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_city
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string City_ar { get; set; }
        public string Region_ar { get; set; }
        public string District_ar { get; set; }
    }
}
