//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class orientation_training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orientation_training()
        {
            this.volunteer_profile = new HashSet<volunteer_profile>();
        }
    
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; } 
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public string VolunteersIds { get; set; }
        public Nullable<System.DateTime> OTDateEnd { get; set; }
        public string SchoolIds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteer_profile> volunteer_profile { get; set; }
    }
}
