//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ot_time
    {
        public int Id { get; set; }
        public int OTId { get; set; }
        public Nullable<System.TimeSpan> ActualStartTime { get; set; }
        public Nullable<System.TimeSpan> ActualEndTime { get; set; }
        public bool IsHoliday { get; set; }
        public bool IsActive { get; set; }
    
        public virtual orientation_training orientation_training { get; set; }
    }
}
