//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantProfile
    {
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public int ParticipantUserID { get; set; }
        public string ParticipantName { get; set; }
        public string ParticipantFirstName { get; set; }
        public string ParticipantFatherName { get; set; }
        public string ParticipantFamilyName { get; set; }
        public string ParticipantMobile { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string ParticipantEmail { get; set; }
        public string NationalID { get; set; }
        public string PhotoPath { get; set; }
        public string ProgrammName1 { get; set; }
        public string ProgrammName2 { get; set; }
        public string ProgrammName3 { get; set; }
        public string FatherMobile { get; set; }
        public string FatherEmail { get; set; }
        public string FacebookAddress { get; set; }
        public string LinkedInAddress { get; set; }
        public string TwitterAddress { get; set; }
        public string SnapChatAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> Age { get; set; }
        public string Stage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsProfileComplete { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> FirstLogin { get; set; }
    }
}
