//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class participant_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participant_profile()
        {
            this.session_participant = new HashSet<session_participant>();
        }

        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public int ParticipantUserID { get; set; }
        public string PhotoPath { get; set; }
        public string ProgrammName2 { get; set; }
        public string ProgrammName3 { get; set; }
        public string FatherEmail { get; set; }
        public string LinkedInAddress { get; set; }
        public Nullable<int> Age { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsProfileComplete { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> FirstLogin { get; set; }
        public string Family { get; set; }
        public string FatherName { get; set; }

        public virtual school school { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_participant> session_participant { get; set; }
    }
}
