//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_actual_time_attendance
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int SessionActualTimeId { get; set; }
    
        public virtual participant_profile participant_profile { get; set; }
        public virtual session_actual_time session_actual_time { get; set; }
    }
}
