//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_proposed_time
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public Nullable<System.TimeSpan> ProposedStartTime { get; set; }
        public Nullable<System.TimeSpan> ProposedEndTime { get; set; }
        public bool IsHoliday { get; set; }
        public bool IsActive { get; set; }
    
        public virtual session session { get; set; }
    }
}
