//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_actual_time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session_actual_time()
        {
            this.session_actual_time_attendance = new HashSet<session_actual_time_attendance>();
        }
    
        public int Id { get; set; }
        public int SessionId { get; set; }
        public Nullable<System.TimeSpan> ActualStartTime { get; set; }
        public Nullable<System.TimeSpan> ActualEndTime { get; set; }
        public bool IsHoliday { get; set; }
        public bool IsActive { get; set; }
    
        public virtual session session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_actual_time_attendance> session_actual_time_attendance { get; set; }
    }
}
