//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_participant
    {
        public int Id { get; set; }
        public int SessionID { get; set; }
        public int ParticipantID { get; set; }
        public string FeedBack { get; set; }
        public Nullable<bool> IsPreEvaluated { get; set; }
        public Nullable<bool> IsCertificateGenerated { get; set; }
        public Nullable<bool> IsPostEvaluated { get; set; }
        public bool VolunteerMarkedAttendence { get; set; }
    
        public virtual participant_profile participant_profile { get; set; }
        public virtual session session { get; set; }
    }
}
