//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Repository.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingProjectEntities : DbContext
    {
        public TrainingProjectEntities()
            : base("name=TrainingProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_user> admin_user { get; set; }
        public virtual DbSet<coordinator_profile> coordinator_profile { get; set; }
        public virtual DbSet<lk_country> lk_country { get; set; }
        public virtual DbSet<lk_role> lk_role { get; set; }
        public virtual DbSet<orientation_training> orientation_training { get; set; }
        public virtual DbSet<participant_profile> participant_profile { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<session_evaluationform_photo> session_evaluationform_photo { get; set; }
        public virtual DbSet<session_evaluationform_result> session_evaluationform_result { get; set; }
        public virtual DbSet<session_photo> session_photo { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<volunteer_profile> volunteer_profile { get; set; }
        public virtual DbSet<certificate> certificates { get; set; }
        public virtual DbSet<evaluation_cp_post> evaluation_cp_post { get; set; }
        public virtual DbSet<evaluation_murshadee_after> evaluation_murshadee_after { get; set; }
        public virtual DbSet<evaluation_murshadee_before> evaluation_murshadee_before { get; set; }
        public virtual DbSet<evaluation_safeer_post> evaluation_safeer_post { get; set; }
        public virtual DbSet<evaluation_syc_post_part1> evaluation_syc_post_part1 { get; set; }
        public virtual DbSet<evaluation_syc_post_part2> evaluation_syc_post_part2 { get; set; }
        public virtual DbSet<evaluation_syc_pre_part1> evaluation_syc_pre_part1 { get; set; }
        public virtual DbSet<evaluation_syc_pre_part2> evaluation_syc_pre_part2 { get; set; }
        public virtual DbSet<lk_city> lk_city { get; set; }
        public virtual DbSet<lk_evaluation_form> lk_evaluation_form { get; set; }
        public virtual DbSet<evaluation_cp_pre> evaluation_cp_pre { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<evaluation_safeer_pre> evaluation_safeer_pre { get; set; }
        public virtual DbSet<session_participant> session_participant { get; set; }
        public virtual DbSet<evaluation_pf_post> evaluation_pf_post { get; set; }
        public virtual DbSet<evaluation_pf_pre> evaluation_pf_pre { get; set; }
        public virtual DbSet<evaluation_volunteer_coordinator> evaluation_volunteer_coordinator { get; set; }
        public virtual DbSet<evaluation_coordinator> evaluation_coordinator { get; set; }
        public virtual DbSet<evaluation_volunteer> evaluation_volunteer { get; set; }
        public virtual DbSet<funder_profile> funder_profile { get; set; }
        public virtual DbSet<session_actual_time> session_actual_time { get; set; }
        public virtual DbSet<session_proposed_time> session_proposed_time { get; set; }
    }
}
