//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coordinator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranningWebApp.Resource.Coordinator", typeof(Coordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new School Coordinator.
        /// </summary>
        public static string AddnewSchoolCoordinator {
            get {
                return ResourceManager.GetString("AddnewSchoolCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new subcoordinator.
        /// </summary>
        public static string AddNewSubcoordinator {
            get {
                return ResourceManager.GetString("AddNewSubcoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add School Coordinator.
        /// </summary>
        public static string AddSchoolCoordinator {
            get {
                return ResourceManager.GetString("AddSchoolCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Profile.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete school registration form.
        /// </summary>
        public static string Completeregisterationform {
            get {
                return ResourceManager.GetString("Completeregisterationform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details.
        /// </summary>
        public static string Contactdetails {
            get {
                return ResourceManager.GetString("Contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator Email.
        /// </summary>
        public static string CoordinatorEmail {
            get {
                return ResourceManager.GetString("CoordinatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string CoordinatorLabel {
            get {
                return ResourceManager.GetString("CoordinatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator Name.
        /// </summary>
        public static string CoordinatorName {
            get {
                return ResourceManager.GetString("CoordinatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we will get back to you shortly. Currently it logout from the system..
        /// </summary>
        public static string cordErrorMsg {
            get {
                return ResourceManager.GetString("cordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Emailaddress {
            get {
                return ResourceManager.GetString("Emailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gregorian.
        /// </summary>
        public static string Gorgian {
            get {
                return ResourceManager.GetString("Gorgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have TOT Certificate?.
        /// </summary>
        public static string HaveTOTCertificate {
            get {
                return ResourceManager.GetString("HaveTOTCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri.
        /// </summary>
        public static string Hijri {
            get {
                return ResourceManager.GetString("Hijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        public static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid value.
        /// </summary>
        public static string LatError {
            get {
                return ResourceManager.GetString("LatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Session.
        /// </summary>
        public static string NoOfSession {
            get {
                return ResourceManager.GetString("NoOfSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Certificates.
        /// </summary>
        public static string OtherCertificates {
            get {
                return ResourceManager.GetString("OtherCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other details.
        /// </summary>
        public static string Otherdetails {
            get {
                return ResourceManager.GetString("Otherdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registeration {
            get {
                return ResourceManager.GetString("Registeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Coordinator.
        /// </summary>
        public static string SchoolCoordinator {
            get {
                return ResourceManager.GetString("SchoolCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School FaceBook.
        /// </summary>
        public static string SchoolFaceBook {
            get {
                return ResourceManager.GetString("SchoolFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Geo Location (Enter google map url).
        /// </summary>
        public static string SchoolGeoLocation {
            get {
                return ResourceManager.GetString("SchoolGeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Geo Locations.
        /// </summary>
        public static string SchoolGeoLocations {
            get {
                return ResourceManager.GetString("SchoolGeoLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Google Account.
        /// </summary>
        public static string SchoolGoogleAccount {
            get {
                return ResourceManager.GetString("SchoolGoogleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Guard Mobile.
        /// </summary>
        public static string SchoolGuardMobile {
            get {
                return ResourceManager.GetString("SchoolGuardMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Guard Name.
        /// </summary>
        public static string SchoolGuardName {
            get {
                return ResourceManager.GetString("SchoolGuardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School ID.
        /// </summary>
        public static string SchoolID {
            get {
                return ResourceManager.GetString("SchoolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Linkedin Account.
        /// </summary>
        public static string SchoolLinkedinAccount {
            get {
                return ResourceManager.GetString("SchoolLinkedinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view school location.
        /// </summary>
        public static string schoollocationmsg {
            get {
                return ResourceManager.GetString("schoollocationmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Locations.
        /// </summary>
        public static string SchoolLocations {
            get {
                return ResourceManager.GetString("SchoolLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Manager Email.
        /// </summary>
        public static string SchoolManagerEmail {
            get {
                return ResourceManager.GetString("SchoolManagerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Manager Mobile.
        /// </summary>
        public static string SchoolManagerMobile {
            get {
                return ResourceManager.GetString("SchoolManagerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Manager Name.
        /// </summary>
        public static string SchoolManagerName {
            get {
                return ResourceManager.GetString("SchoolManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School registration details.
        /// </summary>
        public static string schoolregisterationdetail {
            get {
                return ResourceManager.GetString("schoolregisterationdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Website.
        /// </summary>
        public static string SchoolWebsite {
            get {
                return ResourceManager.GetString("SchoolWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School YouTube.
        /// </summary>
        public static string SchoolYouTube {
            get {
                return ResourceManager.GetString("SchoolYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator profile.
        /// </summary>
        public static string ShowCordProfile {
            get {
                return ResourceManager.GetString("ShowCordProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Profile.
        /// </summary>
        public static string ShowProfile {
            get {
                return ResourceManager.GetString("ShowProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Of School.
        /// </summary>
        public static string StageOfSchool {
            get {
                return ResourceManager.GetString("StageOfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcoordinator.
        /// </summary>
        public static string Subcoordinator {
            get {
                return ResourceManager.GetString("Subcoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOT Certificate.
        /// </summary>
        public static string TOTCertificate {
            get {
                return ResourceManager.GetString("TOTCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of School.
        /// </summary>
        public static string TypeOfSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Uploaded Document.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Activity 1 .
        /// </summary>
        public static string VolunteerActivity1 {
            get {
                return ResourceManager.GetString("VolunteerActivity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Activity 2.
        /// </summary>
        public static string VolunteerActivity2 {
            get {
                return ResourceManager.GetString("VolunteerActivity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Activity 3.
        /// </summary>
        public static string VolunteerActivity3 {
            get {
                return ResourceManager.GetString("VolunteerActivity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
