//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranningWebApp.Resource.OT", typeof(OT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new OT.
        /// </summary>
        public static string AddnewOT {
            get {
                return ResourceManager.GetString("AddnewOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company program.
        /// </summary>
        public static string CompanyProgram {
            get {
                return ResourceManager.GetString("CompanyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Mobile.
        /// </summary>
        public static string ContactPersonMobile {
            get {
                return ResourceManager.GetString("ContactPersonMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name.
        /// </summary>
        public static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Phone.
        /// </summary>
        public static string ContactPersonPhone {
            get {
                return ResourceManager.GetString("ContactPersonPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend of earth.
        /// </summary>
        public static string FriendOfEarth {
            get {
                return ResourceManager.GetString("FriendOfEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri.
        /// </summary>
        public static string Hijri {
            get {
                return ResourceManager.GetString("Hijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its my business.
        /// </summary>
        public static string ItsMyBusiness {
            get {
                return ResourceManager.GetString("ItsMyBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership program.
        /// </summary>
        public static string LeadershipProgram {
            get {
                return ResourceManager.GetString("LeadershipProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Location.
        /// </summary>
        public static string MapLocation {
            get {
                return ResourceManager.GetString("MapLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New OT.
        /// </summary>
        public static string NewOT {
            get {
                return ResourceManager.GetString("NewOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of attendene.
        /// </summary>
        public static string NumberOfattendene {
            get {
                return ResourceManager.GetString("NumberOfattendene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation Training.
        /// </summary>
        public static string OrientationTraining {
            get {
                return ResourceManager.GetString("OrientationTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Date.
        /// </summary>
        public static string OTDate {
            get {
                return ResourceManager.GetString("OTDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Stataus.
        /// </summary>
        public static string OTStatus {
            get {
                return ResourceManager.GetString("OTStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal economic.
        /// </summary>
        public static string PersonalEconomic {
            get {
                return ResourceManager.GetString("PersonalEconomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal finance.
        /// </summary>
        public static string PersonalFinance {
            get {
                return ResourceManager.GetString("PersonalFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal life planning.
        /// </summary>
        public static string PersonalLifePlanning {
            get {
                return ResourceManager.GetString("PersonalLifePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm Name.
        /// </summary>
        public static string ProgrammName {
            get {
                return ResourceManager.GetString("ProgrammName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School List.
        /// </summary>
        public static string SchoolList {
            get {
                return ResourceManager.GetString("SchoolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer your carrer.
        /// </summary>
        public static string SteerYourCarrer {
            get {
                return ResourceManager.GetString("SteerYourCarrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Name.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success skils.
        /// </summary>
        public static string SuccessSkils {
            get {
                return ResourceManager.GetString("SuccessSkils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer List.
        /// </summary>
        public static string VolunteerList {
            get {
                return ResourceManager.GetString("VolunteerList", resourceCulture);
            }
        }
    }
}
