//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranningWebApp.Resource.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Detail.
        /// </summary>
        public static string CoursesDetail {
            get {
                return ResourceManager.GetString("CoursesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date-Changed.
        /// </summary>
        public static string DateChanged {
            get {
                return ResourceManager.GetString("DateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string DownloadPDF {
            get {
                return ResourceManager.GetString("DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Report.
        /// </summary>
        public static string GeneralReport {
            get {
                return ResourceManager.GetString("GeneralReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Partners.
        /// </summary>
        public static string NoofPartners {
            get {
                return ResourceManager.GetString("NoofPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not-Participated.
        /// </summary>
        public static string NotParticipated {
            get {
                return ResourceManager.GetString("NotParticipated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cities.
        /// </summary>
        public static string Numberofcities {
            get {
                return ResourceManager.GetString("Numberofcities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Coordinators.
        /// </summary>
        public static string NumberofCoordinators {
            get {
                return ResourceManager.GetString("NumberofCoordinators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Courses.
        /// </summary>
        public static string NumberofCourses {
            get {
                return ResourceManager.GetString("NumberofCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Female Students.
        /// </summary>
        public static string NumberofFemaleParticipants {
            get {
                return ResourceManager.GetString("NumberofFemaleParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Female session.
        /// </summary>
        public static string NumberofFemalesession {
            get {
                return ResourceManager.GetString("NumberofFemalesession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Female Students.
        /// </summary>
        public static string NumberofFemaleStudents {
            get {
                return ResourceManager.GetString("NumberofFemaleStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Male Students.
        /// </summary>
        public static string NumberofMaleParticipants {
            get {
                return ResourceManager.GetString("NumberofMaleParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Male session.
        /// </summary>
        public static string NumberofMalesession {
            get {
                return ResourceManager.GetString("NumberofMalesession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Male Students.
        /// </summary>
        public static string NumberofMaleStudents {
            get {
                return ResourceManager.GetString("NumberofMaleStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Partners.
        /// </summary>
        public static string NumberofPartners {
            get {
                return ResourceManager.GetString("NumberofPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Partners with Funding type.
        /// </summary>
        public static string NumberofPartnerswithFundingtype {
            get {
                return ResourceManager.GetString("NumberofPartnerswithFundingtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Partners within Partner type.
        /// </summary>
        public static string NumberofPartnerswithinPartnertype {
            get {
                return ResourceManager.GetString("NumberofPartnerswithinPartnertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Post Evaluations.
        /// </summary>
        public static string NumberofPostEvaluations {
            get {
                return ResourceManager.GetString("NumberofPostEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pre Evaluations.
        /// </summary>
        public static string NumberofPreEvaluations {
            get {
                return ResourceManager.GetString("NumberofPreEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Schools.
        /// </summary>
        public static string NumberofSchools {
            get {
                return ResourceManager.GetString("NumberofSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sessions.
        /// </summary>
        public static string NumberofSessions {
            get {
                return ResourceManager.GetString("NumberofSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Students.
        /// </summary>
        public static string NumberofStudents {
            get {
                return ResourceManager.GetString("NumberofStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of students with volunteers per session.
        /// </summary>
        public static string Numberofstudentswithvolunteerspersession {
            get {
                return ResourceManager.GetString("Numberofstudentswithvolunteerspersession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Volunteers.
        /// </summary>
        public static string NumberofVolunteers {
            get {
                return ResourceManager.GetString("NumberofVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Volunteers per Session.
        /// </summary>
        public static string NumberofVolunteersperSession {
            get {
                return ResourceManager.GetString("NumberofVolunteersperSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of volunteers session.
        /// </summary>
        public static string Numberofvolunteerssession {
            get {
                return ResourceManager.GetString("Numberofvolunteerssession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occured.
        /// </summary>
        public static string Occured {
            get {
                return ResourceManager.GetString("Occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string OutStanding {
            get {
                return ResourceManager.GetString("OutStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Detail.
        /// </summary>
        public static string ParticipantsDetail {
            get {
                return ResourceManager.GetString("ParticipantsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participated.
        /// </summary>
        public static string Participated {
            get {
                return ResourceManager.GetString("Participated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participateds.
        /// </summary>
        public static string Participateds {
            get {
                return ResourceManager.GetString("Participateds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Funding Chart.
        /// </summary>
        public static string PartnerFundingChart {
            get {
                return ResourceManager.GetString("PartnerFundingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Type.
        /// </summary>
        public static string PartnerType {
            get {
                return ResourceManager.GetString("PartnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Type Chart.
        /// </summary>
        public static string PartnerTypeChart {
            get {
                return ResourceManager.GetString("PartnerTypeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports1 {
            get {
                return ResourceManager.GetString("Reports1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Registraions and Number of Students Chart.
        /// </summary>
        public static string SchoolRegistraionsandNumberofStudentsChart {
            get {
                return ResourceManager.GetString("SchoolRegistraionsandNumberofStudentsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Registration.
        /// </summary>
        public static string SchoolRegistration {
            get {
                return ResourceManager.GetString("SchoolRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year.
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        public static string Sept {
            get {
                return ResourceManager.GetString("Sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Name.
        /// </summary>
        public static string SessionName {
            get {
                return ResourceManager.GetString("SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Students.
        /// </summary>
        public static string SessionParticipants {
            get {
                return ResourceManager.GetString("SessionParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Students Chart.
        /// </summary>
        public static string SessionParticipantsChart {
            get {
                return ResourceManager.GetString("SessionParticipantsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        public static string Stages {
            get {
                return ResourceManager.GetString("Stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Courses.
        /// </summary>
        public static string TotalCourses {
            get {
                return ResourceManager.GetString("TotalCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Courses by Stages.
        /// </summary>
        public static string TotalCoursesbyStages {
            get {
                return ResourceManager.GetString("TotalCoursesbyStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Courses by Year.
        /// </summary>
        public static string TotalCoursesbyYear {
            get {
                return ResourceManager.GetString("TotalCoursesbyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Students.
        /// </summary>
        public static string TotalNumberofParticipants {
            get {
                return ResourceManager.GetString("TotalNumberofParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of sessions.
        /// </summary>
        public static string TotalNumberofsessions {
            get {
                return ResourceManager.GetString("TotalNumberofsessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Students.
        /// </summary>
        public static string TotalNumberofStudents {
            get {
                return ResourceManager.GetString("TotalNumberofStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total School Students.
        /// </summary>
        public static string TotalSchoolParticipants {
            get {
                return ResourceManager.GetString("TotalSchoolParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Session in School Students.
        /// </summary>
        public static string TotalSessioninSchoolParticipants {
            get {
                return ResourceManager.GetString("TotalSessioninSchoolParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of sessions.
        /// </summary>
        public static string TotatNumberofsessions {
            get {
                return ResourceManager.GetString("TotatNumberofsessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Detail Chart.
        /// </summary>
        public static string VolunteerDetailChart {
            get {
                return ResourceManager.GetString("VolunteerDetailChart", resourceCulture);
            }
        }
    }
}
