//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranningWebApp.Resource.SessionX", typeof(SessionX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add In Bulk.
        /// </summary>
        public static string AddInBulk {
            get {
                return ResourceManager.GetString("AddInBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new session.
        /// </summary>
        public static string Addnewsession {
            get {
                return ResourceManager.GetString("Addnewsession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested DateApproved by Admin.
        /// </summary>
        public static string ApprovedbyAdmin {
            get {
                return ResourceManager.GetString("ApprovedbyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Sessions.
        /// </summary>
        public static string AssignSessions {
            get {
                return ResourceManager.GetString("AssignSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign This Session.
        /// </summary>
        public static string AssignThisSession {
            get {
                return ResourceManager.GetString("AssignThisSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Date.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Kit Received By School.
        /// </summary>
        public static string ConfirmKitReceivedBySchool {
            get {
                return ResourceManager.GetString("ConfirmKitReceivedBySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Sample Excel.
        /// </summary>
        public static string DownloadExcel {
            get {
                return ResourceManager.GetString("DownloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Back.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Up Coordinator Form.
        /// </summary>
        public static string FillUpCoordinatorForm {
            get {
                return ResourceManager.GetString("FillUpCoordinatorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill up volunteer evaluation.
        /// </summary>
        public static string Fillupvolunteerevaluation {
            get {
                return ResourceManager.GetString("Fillupvolunteerevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri.
        /// </summary>
        public static string Hijri {
            get {
                return ResourceManager.GetString("Hijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete.
        /// </summary>
        public static string MarkComplete {
            get {
                return ResourceManager.GetString("MarkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Completed.
        /// </summary>
        public static string MarkCompleted {
            get {
                return ResourceManager.GetString("MarkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Student Attendance.
        /// </summary>
        public static string MarkStudentAttendense {
            get {
                return ResourceManager.GetString("MarkStudentAttendense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        public static string NewSession {
            get {
                return ResourceManager.GetString("NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Actual Students.
        /// </summary>
        public static string NumberofActualStudents {
            get {
                return ResourceManager.GetString("NumberofActualStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Students.
        /// </summary>
        public static string NumberofStudents {
            get {
                return ResourceManager.GetString("NumberofStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Purpose.
        /// </summary>
        public static string ProgramPurpose {
            get {
                return ResourceManager.GetString("ProgramPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Date.
        /// </summary>
        public static string ProposedDate {
            get {
                return ResourceManager.GetString("ProposedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested End Date.
        /// </summary>
        public static string RequestedEndDate {
            get {
                return ResourceManager.GetString("RequestedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Start Date.
        /// </summary>
        public static string RequestedStartDate {
            get {
                return ResourceManager.GetString("RequestedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request This Session.
        /// </summary>
        public static string RequestThisSession {
            get {
                return ResourceManager.GetString("RequestThisSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Proposed Date.
        /// </summary>
        public static string SchoolProposedDate {
            get {
                return ResourceManager.GetString("SchoolProposedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the kit by Mail Courier.
        /// </summary>
        public static string SendthekitbyMailCourier {
            get {
                return ResourceManager.GetString("SendthekitbyMailCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Details.
        /// </summary>
        public static string SessionDetail {
            get {
                return ResourceManager.GetString("SessionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has occured.
        /// </summary>
        public static string Sessionhasoccured {
            get {
                return ResourceManager.GetString("Sessionhasoccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Management.
        /// </summary>
        public static string SessionManagement {
            get {
                return ResourceManager.GetString("SessionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is marked completed by Volunteer.
        /// </summary>
        public static string SessionMarkedCompleted {
            get {
                return ResourceManager.GetString("SessionMarkedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session marked completed by volunteer.
        /// </summary>
        public static string Sessionmarkedcompletedbyvolunteer {
            get {
                return ResourceManager.GetString("Sessionmarkedcompletedbyvolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is marked completed by Coordinator.
        /// </summary>
        public static string SessionMarkedCompletedCoordniator {
            get {
                return ResourceManager.GetString("SessionMarkedCompletedCoordniator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Attendance.
        /// </summary>
        public static string StudentAttendense {
            get {
                return ResourceManager.GetString("StudentAttendense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Certificate.
        /// </summary>
        public static string StudentCertificate {
            get {
                return ResourceManager.GetString("StudentCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Evaluation.
        /// </summary>
        public static string StudentEvaluation {
            get {
                return ResourceManager.GetString("StudentEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        public static string StudentManagement {
            get {
                return ResourceManager.GetString("StudentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student attendense of session..
        /// </summary>
        public static string StudnetAttendence {
            get {
                return ResourceManager.GetString("StudnetAttendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Post Evaluation.
        /// </summary>
        public static string SubmitPostEvaluation {
            get {
                return ResourceManager.GetString("SubmitPostEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Pre Evaluation.
        /// </summary>
        public static string SubmitPreEvaluation {
            get {
                return ResourceManager.GetString("SubmitPreEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group.
        /// </summary>
        public static string TargetGroup {
            get {
                return ResourceManager.GetString("TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload/Add evluation form photo.
        /// </summary>
        public static string UploadAddevluationformphoto {
            get {
                return ResourceManager.GetString("UploadAddevluationformphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload/Add session form photo.
        /// </summary>
        public static string UploadAddsessionformphoto {
            get {
                return ResourceManager.GetString("UploadAddsessionformphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Excel.
        /// </summary>
        public static string UploadExcel {
            get {
                return ResourceManager.GetString("UploadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photos.
        /// </summary>
        public static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Certificate.
        /// </summary>
        public static string ViewCertificate {
            get {
                return ResourceManager.GetString("ViewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Certificate.
        /// </summary>
        public static string VolunteerCertificate {
            get {
                return ResourceManager.GetString("VolunteerCertificate", resourceCulture);
            }
        }
    }
}
